Update PHP constraints to allow v8.3
laminas/laminas-diactoros pull request #176
Opened 2023-10-27 18:31 UTC by ADmad

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | yes
| QA            | no

### Description

Refs #175

2023-10-27 19:01 UTC, ADmad commented
The "QA Checks' failure seems to be due to a bug in psalm which is addressed here https://github.com/vimeo/psalm/pull/10186 but hasn't been released yet.

2023-10-29 15:09 UTC, Ocramius requested changes

2023-10-29 15:09 UTC, Ocramius commented on composer.lock
> +            "version": "5.15.0",
Let's not upgrade anything: just the lock file.

Merging up is hell otherwise.

2023-10-29 15:10 UTC, Ocramius commented on composer.lock
> +            "version": "5.15.0",
Also, let's squash in the change that reverts all these lockfile changes :)

2023-10-29 16:17 UTC, Ocramius approved these changes
Thanks @ADmad!

2023-10-29 16:17 UTC, merged

2023-10-29 16:17 UTC, ADmad commented
I reverted the changes and then ran `compose update --lock`, not sure why it downgraded the version for `plugin-api-version`.

2023-10-29 16:25 UTC, ADmad commented
> I reverted the changes and then ran compose update --lock, not sure why it downgraded the version for plugin-api-version.

TIL: The value for `plugin-api-version` in `composer.lock` depends on the composer version used. I had used an older `2.0.4` version of composer hence `plugin-api-version` was set to `2.0.0`.